_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.9.19
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
                - 55
            "2":
                - 1
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.19
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
balanced:
    value: true
batch_size:
    value: 128
epochs:
    value: 34
hidden_layer:
    value: 192
learning_rate:
    value: 1.51160225796637e-05
minority_weight:
    value: 4.145781253469201
optimizer:
    value: Adam
threshold:
    value: 0.16599228782341557
weight_decay:
    value: 0.0010839562877959358
